# -*- coding: utf-8 -*-
"""4112029024第一周作業

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXrF5SVFchWXyH9NpMbK7iJOCt0mDB3y
"""

height=float(input("請輸入身高(m):"))
weight=float(input("請輸入體重(kg):"))
bmi=weight/(height*height)
print("bmi值為",bmi)